- name: 确保.ssh目录存在
  become_user: "{{ greenplum_username }}"
  file:
    path: "~{{ greenplum_username }}/.ssh"
    state: directory
    mode: '0700'

- name: 生成用户的 SSH 密钥对
  become_user: "{{ greenplum_username }}"
  vars:
    ssh_key_file: "~{{ greenplum_username }}/.ssh/id_rsa"
  ansible.builtin.openssh_keypair:
    path: "{{ ssh_key_file }}"
    type: rsa
    size: 2048

- name: 拷贝 SSH 密钥到其他节点
  authorized_key:
    user: "{{ greenplum_username }}"
    key: "{{ lookup('file', '~{{ greenplum_username }}/.ssh/id_rsa.pub') }}"
