- name: 校验 NodeName 是否合法
  assert:
    that: inventory_hostname is match('^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$')
    msg: "NodeName 必须由小写字母、数字，“-”或“.”组成，并且必须以小写字母或数字开头和结尾，请修改重试。"

- name: 校验 greenplum-master 节点数量
  run_once: true
  assert:
    that: groups['greenplum-master']|length == 1
    msg: "请将一个(至多一个)节点到 greenplum-master 节点组中。"

- name: 校验 greenplum-segment 节点数量
  run_once: true
  assert:
    that: groups['greenplum-segment']|length >= 1
    msg: "请将添加至少一个节点到 greenplum-segment 节点组中。"
